export const SUPPORTED_BIOMARKERS: Record<string, { aliases: string[]; category: string }> = {
  "Glucosa": { aliases: ["glucosa", "glucose", "glucemia"], category: "metabolic" },
  "Hemoglobina": { aliases: ["hemoglobina", "hemoglobin"], category: "general" },
  "Hematocrito": { aliases: ["hematocrito", "hematocrit", "hto"], category: "general" },
  "Leucocitos": { aliases: ["leucocitos", "leukocytes", "leucocytes", "wbc", "white blood cells"], category: "immune" },
  "Plaquetas": { aliases: ["plaquetas", "platelet count", "platelets", "plt"], category: "general" },
  "Colesterol total": { aliases: ["colesterol total", "total cholesterol", "cholesterol total"], category: "cardiovascular" },
  "HDL": { aliases: ["hdl", "hdl-c", "colesterol hdl", "hdl cholesterol"], category: "cardiovascular" },
  "LDL": { aliases: ["ldl", "ldl-c", "colesterol ldl", "ldl cholesterol", "ldl directo"], category: "cardiovascular" },
  "Triglicéridos": { aliases: ["trigliceridos", "triglicéridos", "triglycerides"], category: "general" },
  "TSH": { aliases: ["tsh", "thyroid stimulating hormone", "hormona estimulante tiroidea"], category: "hormonal" },
  "T4 libre": { aliases: ["t4 libre", "free t4", "ft4", "tiroxina libre"], category: "hormonal" },
  "T3 libre": { aliases: ["t3 libre", "free t3", "ft3", "triyodotironina libre"], category: "hormonal" },
  "HbA1c": { aliases: ["hba1c", "hemoglobina glicosilada", "glycated hemoglobin", "Hemoglobina A1c"], category: "metabolic" },
  "Insulina en ayunas": { aliases: ["insulina en ayunas", "fasting insulin", "insulina basal"], category: "metabolic" },
  "HOMA-IR": { aliases: ["homa-ir", "homa ir", "homa index"], category: "metabolic" },
  "Vitamina D": { aliases: ["vitamina d", "25-oh d", "25(oh)d", "25 hydroxy vitamin d", "calcidiol"], category: "metabolic" },
  "Ferritina": { aliases: ["ferritina", "ferritin"], category: "general" },
  "Creatinina": { aliases: ["creatinina", "creatinine"], category: "general" },
  "Ácido úrico": { aliases: ["acido urico", "ácido úrico", "uric acid"], category: "general" },
  "PCR ultrasensible": { aliases: ["pcr ultrasensible", "proteina c reactiva ultrasensible", "hs-crp", "hscrp", "ultrasensitive crp"], category: "immune" },
  "Bilirrubina total": { aliases: ["bilirrubina total", "total bilirubin", "bilirubin total"], category: "general" },
  "GOT / AST": { aliases: ["got", "ast", "got / ast", "got-ast", "ast (got)", "sgot"], category: "general" },
  "GPT / ALT": { aliases: ["gpt", "alt", "gpt / alt", "gpt-alt", "alt (gpt)", "sgpt"], category: "general" },
  "Fosfatasa alcalina": { aliases: ["fosfatasa alcalina", "alkaline phosphatase", "alp"], category: "general" },
  "GGT": { aliases: ["ggt", "gamma gt", "gamma-glutamil transferasa", "gamma glutamyl transferase"], category: "general" },
  "Hierro sérico": { aliases: ["hierro serico", "hierro sérico", "serum iron"], category: "general" },
  "Transferrina": { aliases: ["transferrina", "transferrin"], category: "general" },
  "Índice Saturación Transferrina": { aliases: ["indice saturacion transferrina", "indice de saturacion transferrina", "saturacion transferrina", "saturacion de transferrina", "saturacion de la transferrina", "sat transferrina", "transferrin saturation", "saturation transferrin", "%sat transferrina"], category: "general" },
  "Vitamina B12": { aliases: ["vitamina b12", "b12", "cobalamina", "cobalamin"], category: "general" },
  "Ácido fólico": { aliases: ["acido folico", "ácido fólico", "folato", "folic acid"], category: "general" },
  "Calcio total": { aliases: ["calcio total", "total calcium", "calcium total", "serum calcium"], category: "general" },
  "Magnesio": { aliases: ["magnesio", "magnesium"], category: "general" },
  "FSH": { aliases: ["fsh", "follicle stimulating hormone"], category: "hormonal" },
  "Testosterona libre": { aliases: ["testosterona libre", "free testosterone", "testosterona biodisponible"], category: "hormonal" },
  "Filtrado glomerular": { aliases: ["filtrado glomerular", "egfr", "tfg", "estimated glomerular filtration rate"], category: "metabolic" },
  "Urea": { aliases: ["urea", "bun", "blood urea nitrogen"], category: "general" },
  "PSA total": { aliases: ["psa total", "total psa", "antigeno prostatico especifico", "prostate specific antigen"], category: "general" },
  "CA 125": { aliases: ["ca 125", "ca125", "cancer antigen 125"], category: "general" },
  "CEA": { aliases: ["cea", "carcinoembryonic antigen", "antigeno carcinoembrionario"], category: "general" },
}
