export const SUPPORTED_BIOMARKERS: Record<string, { aliases: string[], category: string }> = {
  "Lipoprotein(a)": { aliases: ["lipoproteina a", "lipo(a)", "lp(a)"], category: "cardiovascular" },
  "Apolipoprotein B (ApoB)": { aliases: ["apob", "apolipoproteina b"], category: "cardiovascular" },
  "Triglycerides": { aliases: ["trigliceridos", "triglycerides", "triglicéridos"], category: "cardiovascular" },
  "Total Cholesterol": { aliases: ["colesterol total", "total cholesterol"], category: "cardiovascular" },
  "LDL Cholesterol": { aliases: ["ldl", "ldl-c", "colesterol ldl"], category: "cardiovascular" },
  "HDL Cholesterol": { aliases: ["hdl", "hdl-c", "colesterol hdl"], category: "cardiovascular" },
  "VLDL Cholesterol": { aliases: ["vldl"], category: "cardiovascular" },
  "Non-HDL Cholesterol": { aliases: ["no-hdl", "non-hdl"], category: "cardiovascular" },
  "Total Cholesterol/HDL Ratio": { aliases: ["chol/hdl", "tc/hdl", "indice aterogenico"], category: "cardiovascular" },
  "HDL/LDL Ratio": { aliases: ["hdl/ldl"], category: "cardiovascular" },
  "Homocysteine": { aliases: ["homocisteina", "homocysteine"], category: "cardiovascular" },
  "High-Sensitivity C-Reactive Protein (hs-CRP)": { aliases: ["hs-crp", "pcr ultrasensible", "proteina c reactiva ultrasensible"], category: "immune" },
  "Glucose": { aliases: ["glucosa", "glucose"], category: "metabolic" },
  "Insulin": { aliases: ["insulina", "insulin"], category: "metabolic" },
  "HOMA-IR": { aliases: ["homa ir", "homa-ir"], category: "metabolic" },
  "25-Hydroxy Vitamin D": { aliases: ["vitamina d", "25-oh d"], category: "general" },
  "Zinc": { aliases: ["zinc"], category: "general" },
  "Magnesium": { aliases: ["magnesio", "magnesium"], category: "general" },
  "Iron": { aliases: ["hierro", "iron"], category: "general" },
  "Iron Binding Capacity (TIBC)": { aliases: ["tibc", "capacidad total de union al hierro"], category: "general" },
  "Ferritin": { aliases: ["ferritina", "ferritin"], category: "general" },
  "Calcium": { aliases: ["calcio", "calcium"], category: "general" },
  "Phosphorus": { aliases: ["fosforo", "phosphorus", "phosphate"], category: "general" },
  "Lactate Dehydrogenase (LDH)": { aliases: ["ldh"], category: "general" },
  "Vitamin B9 (Folate – Folic Acid)": { aliases: ["folato", "vitamina b9", "folic acid"], category: "general" },
  "Vitamin B12 (Cobalamin)": { aliases: ["vitamina b12", "cobalamina", "cobalamin"], category: "general" },
  "Urea": { aliases: ["urea"], category: "general" },
  "Creatinine": { aliases: ["creatinina", "creatinine"], category: "general" },
  "Choleride": { aliases: ["cloruro", "chloride", "cloruros"], category: "general" },
  "Potassium": { aliases: ["potasio", "potassium"], category: "general" },
  "Sodium": { aliases: ["sodio", "sodium"], category: "general" },
  "eGFR": { aliases: ["egfr", "filtrado glomerular"], category: "general" },
  "eGFR/Creatinine Ratio": { aliases: ["egfr/creatinina", "egfr/creatinine"], category: "general" },
  "Total Protein": { aliases: ["proteinas totales", "total protein"], category: "general" },
  "Albumin": { aliases: ["albúmina", "albumin"], category: "general" },
  "Albumin/Globulin Ratio (A/G Ratio)": { aliases: ["relacion a/g", "a/g ratio"], category: "general" },
  "Total Bilirubin": { aliases: ["bilirrubina total", "total bilirubin"], category: "general" },
  "Aspartate Transaminase (AST)": { aliases: ["ast", "got"], category: "general" },
  "Alanine Transaminase (ALT)": { aliases: ["alt", "gpt"], category: "general" },
  "Alkaline Phosphatase (ALP)": { aliases: ["alp", "fosfatasa alcalina"], category: "general" },
  "FIB-4 Index": { aliases: ["fib-4", "fib4"], category: "general" },
  "White Blood Cell (WBC) – Leukocytes": { aliases: ["wbc", "leucocitos"], category: "immune" },
  "Neutrophils": { aliases: ["neutrofilos", "neutrophils"], category: "immune" },
  "Lymphocytes": { aliases: ["linfocitos", "lymphocytes"], category: "immune" },
  "Monocytes": { aliases: ["monocitos", "monocytes"], category: "immune" },
  "Eosinophils": { aliases: ["eosinofilos", "eosinophils"], category: "immune" },
  "Basophils": { aliases: ["basofilos", "basophils"], category: "immune" },
  "Platelet Count": { aliases: ["plaquetas", "platelet"], category: "immune" },
}
